---
title: "Comments on De Oliveira and Jacobson"
author: "Simon Halliday (Smith College)"
date: "2015-November-23"
output: ioslides_presentation
    #css: io2013.css
    #logo: logo2.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Summary

- Time preferences over outcomes for others is NB for policy
- Big research gap: especially because of incurring *disutility* of effort
- What about getting others to exert effort instead of you?
- Does *increasing* social distance affect the weight one gives to another's effort? 
- Or, does *decreasing* social distance remove information asymmetry about personal characteristics, such as (im)patience? 

## Main Results

1. "Law of Supply": Effort supplied increases with higher "price" for effort (substituting across time). 
2. Treatments consistent with now-versus-later at the extremes. 
3. Separate consideration of own vs. others w.r.t. minute rates (more at moderate rates). 
4. Separate pool into 0 vs. 60 minute choices: People choose 60 later for others much more often than for themselves. 
    - driven by strangers not friends

## Comments about things you can't do anything about

- Why the asymmetry of the task rates over 0.5 and 0.75, but increasing up to 4? 
    - e.g. if you're going up to 4, why not decrease to 0.25? 
    - I think Augenblick et al. 2015 was symmetrical around 1. 
- Why did you not incentivize the beliefs about others and impatience?
    - Worry: survey responses differ from incentivized choices

##Treatments?
- Why not have a treatment "Friend-Stranger"?
    - exclude 'own', just tradeoffs of others
    - disentangle even more the relationship between 'friend' and 'other'. 
    - Motivated by your result on perceptions of strangers' & friends' patience 

##Comment re: Climate Change
- I'm perplexed w.r.t. your discussion of climate change 
    - we economists interpret patience in the following way: a higher discount factor for effort 
    -  a "more patient" person will prefer to exert effort *now* at higher minute rates (sensible)
    - but says that their friends won't
    - may not gel with many peoples' intuitive understanding of '(im)patience' (I was trying to explain your paper to my wife & a friend, which is when this came up)
    - "they" incur the costs to deal with climate change in the future, whereas "I" am... "willing to pay now". Right? 
    - Admittedly, I could have simply been confused on a quick reading. 

##Comment: Pairing Data & Samples

- Friend data: are there differences in friend-Gender pairings and perceived differences in patience? 
    - e.g. M-M; M-F; F-M, F-F. 
- I got a little confused: 
    - I saw that 1 of 100 subjects exerted zero effort (p. 11)
    - But you had 3/110 who didn't return... 
    - And 5/63 completed zero in the return session
- I wasn't sure how to add & compare these (in my quick reading)
- Perhaps make clearer somewhere the various samples

## Comment: Friends vs. Strangers
###Some things you can do something about, some not
- I wasn't sure from the paper, but I suspect that your questionnaire could have used a question like "How many people in the lab right now are you friends with?" 
    - I'm concerned that 'strangers' may not actually be total strangers (just *slightly* less social distance), especially if subjects were asked "to bring friends to the lab"
    - therefore your estimates may *underestimate* the difference between actual strangers and others 
    - therefore perhaps provide a *lower bound*? 
    - perhaps regressions should be clustered at the level of the session?
    
        
##Other comments

- I was amazed at how low the rate of attrition was (3/110 subjects) (net $45 payment)
- Why do you assume people are never spiteful? 
    - Why wouldn't I give you more time in the future for spiteful reasons? (we could check this against the results, but I may bound your results, maybe?)
    - Plenty of evidence that people can be nasty (e.g. Abbink & Sadrieh, 2009, Zizzo, various others)
- What stops a subject from just sitting there and playing on their phone? (you answer this... )
