---
title: "Team Project Guidelines"
author: "Simon Halliday"
date: "2015-September -29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Ideas
If you're in a particular group, I would recommend that *before* you look in journals you open a scratch document where people can brainstorm ideas that they're interested in. 

## Journals
For your projects, you should look mainly at journal articles. There are a variety of really good journals that deal with topics in experimental and behavioral economics. Some of the journals are "general interest" journals where they will have the occasional paper on behavioral economics, others are more focused on topics related to behavioral economics. 

Before doing anything else, I recommend that you use google scholar: [scholar.google.com](http://scholar.google.com) to do searches for academic papers that involve the topic you are interested in. Use relevant keywords. 

###General Interest Journals or journals that occasionally include experiments

- American Economic Review 
- AEJ: Microeconomics 
- Journal of Economic Literature
- Journal of Economic Perspectives
- Southern Economic Journal 
- Economics Letters
- Economic Inquiry
- Journal of the European Economic Association 
- Journal of Public Economics

###Field Journals (specific to behavioral economics, experimental economics and game theory)

- Experimental Economics
- Games and Economic Behavior
- Journal of Economic Psychology
- Journal of Economic Behavior and Organization
- Journal of Behavioral and Experimental Economics (formerly the Journal of Socio-Economics)
- Journal of the Economic Science Association 
- Review of Behavioral Economics
- Journal of Risk and Uncertainty
- Behavioral and Brain Sciences

###General Science Journals that Include Behavioral/Experimental Economics
- Science
- Nature
- PNAS
- PLOS One

###Organizations involved with Beahvioral and Experimental Economics

- ESA: The Economic Science Association
- IAREP: International Association for Research in Economic Psychology
- ICABEEP: The International Confederation for the Advancement of Behavioral Economics and Economic Psychology
- SABE: The Society for the Advancement of Behavioral Economics
- IFREE: International Foundation for Research in Experimental Economics [http://ifreeweb.org](http://ifreeweb.org)



### A non-exhaustive list of fantastic female behavioral & experimental economists

- Elinor Ostrom (common property, social preferences)
- Elizabeth Hoffman (Endowment Effect & Social Preferences) - she's also a Smith Alum
- Elizabeth Rutstrom (Risk)
- Muriel Niederle (Gender & Prefs)
- Lise Vesterlund (Fairness & gender)
- Catherine Eckel (generosity, risk, gender)
- Alison Booth (mostly labor, but some behavioral on competition & risk preferences)
- Rachel Kranton (identity, networks, institutions)
- Marianne Bertrand (generally applied econ, but some behavioral)
- Ulrike Malmendier (social preferences, micro theory, lots)
- Oriana Bandiera (social preferences, cooperation, firm behavior)
- Rachel Croson (social prefences, cooperation, gender)
- Rosemarie Nagel (beliefs, trust, bargaining)
- Marie-Claire Villeval (social norms, deceit, self-control, teams)
- Abigail Barr (cooperation, 'lab in the field', social preferences)
- Lata Gangadharan (cooperation, social prefs, gender)
- Iris Bohnet (trust, incentives, betrayal)

