---
title: "Scott Wolla’s Presentation"
author: "Simon Halliday"
date: "2 June 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Main Points

- There's a great deal of theory in econ
- Much of it *confounds* students
- We can engage students by connecting theory to reality
- Build on their *prior knowledge*
- Show them *data* from their real world

##Method 

1. Assess students' prior knowledge (find hooks)
2. What do Econs think about that topic? (apologies to Leijonhufvud)
3. Introduce model 
4. Reinforce with visualization

## Examples used

- minimum wage 
  + supply and demand
  + elasticity
- immigration
  + ppf
  + gains from trade 
  + specialization
  + skills/productivity

## Issues

- Building in ideas of existing assessment of student learning, see, e.g. Bice et al (2014) -- find Bill Goffe and he'll tell you
- False beliefs are hard to correct with data... 
- ... especially when that data relates to politics
- But, the FRED site is great 
(a statistician friend of mine agrees that it's the most data-savvy govt site he's seen, when I showed it to him for our work, dygraphs, heatmaps, etc)

## What about? 

**Make it Stick** - Peter Brown et al (2014)

- interleaved learning
- repetition of topics across many areas
- various other strategies that could be promoted by FRED


## Study Guides/Worksheets
- What about preliminary reading quizzes? 
    + e.g. 3 to 5 MCQs/True-False with insta-feedback
- Are there ways to provide instant feedback to the written answers? (I couldn't tell from the presentation slides, but I know this is being piloted elsewhere); or another way to do this
- The website looks like it'd be amenable to more interactive Q & A
- As you have the infrastructure (questions and answers), seems pretty low cost to implement

##On Data & Reproducing what you did

- What do you do with the data? 
- How could a student do what you did?
- Could I have exercises where I ask students to do what you did with data? 
- Or request similar, but different, data? e.g. unemployment and labor force participation rate
- What about screencasts? 
- Or databases of dashboards? 


